# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-09 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondenceAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('pincode', models.IntegerField(blank=True)),
                ('country', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('pincode', models.IntegerField(blank=True)),
                ('country', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(blank=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10)),
                ('profile_pic', models.ImageField(blank=True, upload_to='')),
                ('birth_date', models.DateField(blank=True)),
                ('correspondence_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='accounts.CorrespondenceAddress')),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('permanent_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent', to='accounts.PermanentAddress')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
