# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-09 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190809_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='correspondence_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='accounts.CorrespondenceAddress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permanent_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent', to='accounts.PermanentAddress'),
        ),
    ]
