# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-10 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190810_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondenceaddress',
            name='city',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='correspondenceaddress',
            name='country',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='correspondenceaddress',
            name='state',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='correspondenceaddress',
            name='street_address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='correspondenceaddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='city',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='country',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='state',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='street_address',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='correspondence_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correspondence', to='accounts.CorrespondenceAddress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permanent_address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent', to='accounts.PermanentAddress'),
        ),
    ]
