# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-11 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190811_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondenceaddress',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='permanentaddress',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
