# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-08-12 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20190812_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=models.TextField(verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(max_length=256),
        ),
    ]
